[package]
name = "ts_xml_define"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.41"
syn = "2.0.108"
roxmltree = "0.21.1"
convert_case = "0.11.0"
proc-macro2 = "1.0.106"

[dev-dependencies]
serde = { version = "1.0.228", features = ["derive"] }
